In [5]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [6]:
# defining the path
path = r'C:\Users\dog\Desktop\Instacart Basket Analysis'

In [9]:
# importing pickle from the previous task
df_orders_products_merged_new = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_new.02.01.pkl'))

In [30]:
# adding new column with identification of the customer type
df_orders_products_merged_new['customer_type'] = np.where(df_orders_products_merged_new['days_since_prior_order'].isnull(), 'new', 'old')

In [31]:
# creating a subset with 1000000 rows
df = df_orders_products_merged_new[:1000000]

In [33]:
#checking if all the data was imported 
df

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_hours,customer_type
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,Soda,77,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,new
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,Soda,77,7,9.0,both,High-range product,Regularly busy,Slowest days,average orders,old
2,473747,1,prior,3,3,12,21.0,196,1,1,...,Soda,77,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,Soda,77,7,9.0,both,High-range product,Least busy,Slowest days,average orders,old
4,431534,1,prior,5,4,15,28.0,196,1,1,...,Soda,77,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2836489,164627,prior,14,0,15,6.0,30489,2,0,...,Original Hummus,67,20,7.5,both,High-range product,Busiest day,Busiest days,Most orders,old
999996,1843600,164632,prior,5,1,19,9.0,30489,2,0,...,Original Hummus,67,20,7.5,both,High-range product,Regularly busy,Busiest days,average orders,old
999997,733106,164632,prior,9,2,22,10.0,30489,3,1,...,Original Hummus,67,20,7.5,both,High-range product,Regularly busy,Regularly busy,average orders,old
999998,1650124,164632,prior,17,6,17,13.0,30489,1,1,...,Original Hummus,67,20,7.5,both,High-range product,Regularly busy,Regularly busy,average orders,old
999999,3378258,164632,prior,22,6,10,15.0,30489,3,1,...,Original Hummus,67,20,7.5,both,High-range product,Regularly busy,Regularly busy,Most orders,old

In [32]:
#checking shape of the data frame
df.shape

(1000000, 21)

In [34]:
#grouping this data frame by product
df.groupby('product_name')

In [35]:
# grouping data frame by department ID and aggregating by orders mean, which will give us AVG of orders per department
df.groupby('department_id').agg({'order_number': ['mean']}).sort_values(('order_number','mean'), ascending = False)

              order_number
                      mean
department_id
16               19.463012
19               19.305237
14               19.246334
4                18.825780
13               17.993423
20               17.599636
7                17.472355
17               11.294069

In [36]:
# same method, without agg function
df.groupby('department_id').order_number.mean().sort_values(ascending = False)

department_id
16    19.463012
19    19.305237
14    19.246334
4     18.825780
13    17.993423
20    17.599636
7     17.472355
17    11.294069
Name: order_number, dtype: float64

In [37]:
# same method, but sort by index
df.groupby('department_id').order_number.mean().sort_index(ascending=False)

department_id
20    17.599636
19    19.305237
17    11.294069
16    19.463012
14    19.246334
13    17.993423
7     17.472355
4     18.825780
Name: order_number, dtype: float64

In [38]:
# same method, without agg function
df.groupby('department_id').order_number.mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [39]:
# same method, but without dots and with sort_index desc. Here Index is by default department ID 
df.groupby('department_id')['order_number'].mean().sort_index(ascending = False)

department_id
20    17.599636
19    19.305237
17    11.294069
16    19.463012
14    19.246334
13    17.993423
7     17.472355
4     18.825780
Name: order_number, dtype: float64

In [40]:
# same method, but sort by reseted index and order mean number
df.groupby('department_id')['order_number'].mean().reset_index().sort_values('order_number', ascending=True)

   department_id  order_number
5             17     11.294069
1              7     17.472355
7             20     17.599636
2             13     17.993423
0              4     18.825780
3             14     19.246334
6             19     19.305237
4             16     19.463012

In [41]:
# MULTIPLE AGGREGATION
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']}).sort_values(('order_number','mean'), ascending = False)

              order_number
                      mean min max
department_id
16               19.463012   1  99
19               19.305237   1  99
14               19.246334   1  99
4                18.825780   1  99
13               17.993423   1  99
20               17.599636   1  99
7                17.472355   1  99
17               11.294069   1  98

In [42]:
# same but sort by index which is department id 
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']}).sort_index(ascending=False)

              order_number
                      mean min max
department_id
20               17.599636   1  99
19               19.305237   1  99
17               11.294069   1  98
16               19.463012   1  99
14               19.246334   1  99
13               17.993423   1  99
7                17.472355   1  99
4                18.825780   1  99

In [43]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

In [ ]:
# aggregatind data with transform

In [45]:
# checking info of the df 
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000000 entries, 0 to 999999
Data columns (total 21 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   order_id                1000000 non-null  int64
 1   user_id                 1000000 non-null  int64
 2   eval_set                1000000 non-null  object
 3   order_number            1000000 non-null  int64
 4   order_dow               1000000 non-null  int64
 5   order_hour_of_day       1000000 non-null  int64
 6   days_since_prior_order  939915 non-null   float64
 7   product_id              1000000 non-null  int64
 8   add_to_cart_order       1000000 non-null  int64
 9   reordered               1000000 non-null  int64
 10  Unnamed: 0              1000000 non-null  int64
 11  product_name            1000000 non-null  object
 12  aisle_id                1000000 non-null  int64
 13  department_id           1000000 non-null  int64
 14  prices                  1000000 non-null  float64
 15  _merge                  1000000 non-null  category
 16  price_range_loc         1000000 non-null  object
 17  busiest_day             1000000 non-null  object
 18  busiest_days_new        1000000 non-null  object
 19  busiest_hours           1000000 non-null  object
 20  customer_type           1000000 non-null  object
dtypes: category(1), float64(2), int64(11), object(7)
memory usage: 161.2+ MB

In [49]:
#checking description of the data frame
df.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0,aisle_id,department_id,prices
count,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,1000000.000000,939915.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,1.710240e+06,101788.547547,18.731714,2.686741,13.272235,10.646367,27119.966748,6.078493,0.769933,27121.711388,44.407396,8.740095,7.819497
std,9.873682e+05,59011.894306,18.563841,2.053382,4.218017,8.467237,15578.819637,5.695749,0.420876,15580.659854,28.925073,6.419989,3.641458
min,5.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,196.000000,1.000000,0.000000,195.000000,21.000000,4.000000,1.000000
25%,8.555392e+05,50641.000000,5.000000,1.000000,10.000000,5.000000,13176.000000,2.000000,1.000000,13176.000000,24.000000,4.000000,6.300000
50%,1.709734e+06,101164.000000,12.000000,2.000000,13.000000,7.000000,26088.000000,4.000000,1.000000,26089.000000,24.000000,4.000000,9.000000
75%,2.565079e+06,152132.000000,27.000000,5.000000,16.000000,14.000000,47766.000000,8.000000,1.000000,47770.000000,67.000000,16.000000,10.300000
max,3.421068e+06,206209.000000,99.000000,6.000000,23.000000,30.000000,49235.000000,99.000000,1.000000,49239.000000,121.000000,20.000000,14.800000

In [51]:
#2 spliting data into groups based on the used ID column
df_orders_products_merged_new['max_order'] = df_orders_products_merged_new.groupby(['user_id'])['order_number'].transform(np.max)

In [56]:
df_orders_products_merged_new.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_hours,customer_type,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,77,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,new,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,77,7,9.0,both,High-range product,Regularly busy,Slowest days,average orders,old,10
2,473747,1,prior,3,3,12,21.0,196,1,1,...,77,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,77,7,9.0,both,High-range product,Least busy,Slowest days,average orders,old,10
4,431534,1,prior,5,4,15,28.0,196,1,1,...,77,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,10

In [57]:
# creating loyality flags
# 1 defining flags for the loyality check
def customers_loyalty(row):

  if row['max_order'] > 40:
    return 'Loyal Customer'
  elif (row['max_order'] > 10) and (row['max_order'] <= 40):
    return 'Regular Customer'
  elif row['max_order'] <= 10:
    return 'New Customer'
  else: return 'Not enough data'

In [58]:
# applying the same to the sub data frame
df['max_order']= df.groupby(['user_id'])['order_number'].transform(np.max)

In [59]:
# checking if everything worked out
df.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_hours,customer_type,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,77,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,new,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,77,7,9.0,both,High-range product,Regularly busy,Slowest days,average orders,old,10
2,473747,1,prior,3,3,12,21.0,196,1,1,...,77,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,77,7,9.0,both,High-range product,Least busy,Slowest days,average orders,old,10
4,431534,1,prior,5,4,15,28.0,196,1,1,...,77,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,10

In [60]:
#adding new column to the subset of the df
df['customer_loyalty'] = df.apply(customers_loyalty, axis=1)

In [63]:
#checking if that worked out
df.head(20)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_hours,customer_type,max_order,customer_loyalty
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,new,10,New Customer
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,average orders,old,10,New Customer
2,473747,1,prior,3,3,12,21.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,10,New Customer
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,7,9.0,both,High-range product,Least busy,Slowest days,average orders,old,10,New Customer
4,431534,1,prior,5,4,15,28.0,196,1,1,...,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,10,New Customer
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,old,10,New Customer
6,550135,1,prior,7,1,9,20.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,10,New Customer
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,10,New Customer
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,10,New Customer
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,7,9.0,both,High-range product,Least busy,Slowest days,average orders,old,10,New Customer
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,22,Regular Customer
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,22,Regular Customer
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,22,Regular Customer
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,22,Regular Customer
14,487368,15,prior,22,1,10,14.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,22,Regular Customer
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,7,New Customer
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,7,New Customer
17,532817,19,prior,7,4,17,6.0,196,1,1,...,7,9.0,both,High-range product,Least busy,Slowest days,average orders,old,7,New Customer
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,33,Regular Customer
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,7,9.0,both,High-range product,Regularly busy,Slowest days,average orders,old,17,Regular Customer

In [64]:
#setting the limit of the max rowss printed to no limit
pd.options.display.max_rows = None

In [67]:
df.head(100)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_hours,customer_type,max_order,customer_loyalty
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,new,10,New Customer
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,average orders,old,10,New Customer
2,473747,1,prior,3,3,12,21.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,10,New Customer
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,7,9.0,both,High-range product,Least busy,Slowest days,average orders,old,10,New Customer
4,431534,1,prior,5,4,15,28.0,196,1,1,...,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,10,New Customer
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,old,10,New Customer
6,550135,1,prior,7,1,9,20.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,10,New Customer
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,10,New Customer
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,10,New Customer
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,7,9.0,both,High-range product,Least busy,Slowest days,average orders,old,10,New Customer
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,22,Regular Customer
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,22,Regular Customer
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,22,Regular Customer
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,22,Regular Customer
14,487368,15,prior,22,1,10,14.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,22,Regular Customer
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,7,New Customer
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,7,New Customer
17,532817,19,prior,7,4,17,6.0,196,1,1,...,7,9.0,both,High-range product,Least busy,Slowest days,average orders,old,7,New Customer
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,33,Regular Customer
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,7,9.0,both,High-range product,Regularly busy,Slowest days,average orders,old,17,Regular Customer
20,2231262,31,prior,17,3,11,8.0,196,14,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,17,Regular Customer
21,2580647,43,prior,6,4,16,4.0,196,9,0,...,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,9,New Customer
22,2187180,43,prior,9,4,12,3.0,196,1,1,...,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,9,New Customer
23,2497897,52,prior,1,1,9,NaN,196,4,0,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,new,27,Regular Customer
24,1318871,52,prior,2,1,10,7.0,196,5,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,27,Regular Customer
25,1261384,52,prior,3,1,10,7.0,196,3,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,27,Regular Customer
26,580568,52,prior,5,2,10,8.0,196,6,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,27,Regular Customer
27,2428073,52,prior,7,2,7,8.0,196,5,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,old,27,Regular Customer
28,342306,52,prior,9,1,11,7.0,196,5,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,27,Regular Customer
29,1520353,52,prior,10,2,10,8.0,196,4,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,27,Regular Customer
30,2542086,52,prior,11,2,9,7.0,196,3,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,27,Regular Customer
31,944694,52,prior,12,1,16,6.0,196,7,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,27,Regular Customer
32,1268191,52,prior,15,2,11,8.0,196,3,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,27,Regular Customer
33,1122089,52,prior,17,2,10,6.0,196,4,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,27,Regular Customer
34,1498922,52,prior,18,2,10,14.0,196,6,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,27,Regular Customer
35,180919,52,prior,19,3,8,8.0,196,4,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,average orders,old,27,Regular Customer
36,2695875,52,prior,21,5,10,30.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,27,Regular Customer
37,3205960,67,prior,1,3,11,NaN,196,1,0,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,new,23,Regular Customer
38,970922,67,prior,2,1,15,5.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,23,Regular Customer
39,596585,67,prior,3,1,13,7.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,23,Regular Customer
40,2037087,67,prior,4,2,9,8.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,23,Regular Customer
41,2474111,67,prior,5,3,14,8.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,23,Regular Customer
42,1568481,67,prior,6,3,12,7.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,23,Regular Customer
43,2048527,67,prior,8,2,11,7.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,23,Regular Customer
44,2389031,67,prior,9,2,14,7.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,23,Regular Customer
45,2378562,67,prior,10,1,10,6.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,23,Regular Customer
46,1515698,67,prior,11,1,11,7.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,23,Regular Customer
47,1928050,67,prior,12,2,12,8.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,23,Regular Customer
48,1949274,67,prior,13,1,10,6.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,23,Regular Customer
49,551869,67,prior,14,1,9,7.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,23,Regular Customer
50,768572,67,prior,16,4,10,9.0,196,1,1,...,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,23,Regular Customer
51,150528,67,prior,18,5,16,4.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,23,Regular Customer
52,29758,67,prior,19,0,14,9.0,196,2,1,...,7,9.0,both,High-range product,Busiest day,Busiest days,Most orders,old,23,Regular Customer
53,1558976,67,prior,21,1,9,5.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,23,Regular Customer
54,863974,67,prior,22,1,11,14.0,196,3,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,23,Regular Customer
55,2308399,67,prior,23,1,14,14.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,23,Regular Customer
56,2759128,81,prior,3,1,9,14.0,196,2,0,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,5,New Customer
57,1812985,81,prior,5,2,20,30.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,old,5,New Customer
58,1889835,82,prior,1,3,15,NaN,196,6,0,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,new,19,Regular Customer
59,499460,82,prior,3,5,10,5.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,19,Regular Customer
60,2728456,82,prior,4,0,11,16.0,196,1,1,...,7,9.0,both,High-range product,Busiest day,Busiest days,Most orders,old,19,Regular Customer
61,2653743,82,prior,6,4,9,13.0,196,5,1,...,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,19,Regular Customer
62,1358880,82,prior,9,1,10,30.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,19,Regular Customer
63,343588,82,prior,10,2,11,1.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,19,Regular Customer
64,3034663,82,prior,15,2,11,12.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,19,Regular Customer
65,147262,82,prior,18,1,13,7.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,19,Regular Customer
66,3144004,82,prior,19,2,15,8.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,19,Regular Customer
67,2126069,98,prior,3,0,9,25.0,196,7,0,...,7,9.0,both,High-range product,Busiest day,Busiest days,Most orders,old,14,Regular Customer
68,2210120,98,prior,7,5,14,5.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,14,Regular Customer
69,681011,98,prior,9,3,9,30.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,14,Regular Customer
70,2846344,98,prior,11,4,13,15.0,196,2,1,...,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,14,Regular Customer
71,747431,98,prior,12,6,13,30.0,196,4,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,14,Regular Customer
72,2383054,98,prior,13,4,11,30.0,196,1,1,...,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,14,Regular Customer
73,1993729,98,prior,14,5,8,8.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,old,14,Regular Customer
74,1403849,109,prior,3,3,17,9.0,196,5,0,...,7,9.0,both,High-range product,Regularly busy,Slowest days,average orders,old,3,New Customer
75,520620,120,prior,1,3,11,NaN,196,2,0,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,new,3,New Customer
76,3273029,120,prior,3,2,8,19.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,old,3,New Customer
77,1861943,185,prior,2,1,12,25.0,196,10,0,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,2,New Customer
78,2040988,195,prior,1,1,14,NaN,196,2,0,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,new,57,Loyal Customer
79,1680569,195,prior,8,1,9,4.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,57,Loyal Customer
80,276171,195,prior,19,5,11,3.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,57,Loyal Customer
81,2744976,195,prior,22,5,10,7.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,57,Loyal Customer
82,2781919,195,prior,25,1,14,4.0,196,1,1,...,7,9.0,both,High-range product,Regularly busy,Busiest days,Most orders,old,57,Loyal Customer
83,1738718,195,prior,31,2,8,4.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,old,57,Loyal Customer
84,3058369,195,prior,34,3,10,6.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,57,Loyal Customer
85,1485596,195,prior,37,2,15,0.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,57,Loyal Customer
86,417035,195,prior,40,3,16,2.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,57,Loyal Customer
87,1615297,195,prior,47,5,10,2.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,57,Loyal Customer
88,1765587,195,prior,52,3,12,2.0,196,3,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,Most orders,old,57,Loyal Customer
89,745908,195,prior,57,4,11,3.0,196,3,1,...,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,57,Loyal Customer
90,2505656,222,prior,17,2,12,1.0,196,2,0,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,38,Regular Customer
91,3268370,222,prior,38,5,15,1.0,196,6,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,38,Regular Customer
92,2016711,290,prior,9,5,19,6.0,196,8,0,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,old,45,Loyal Customer
93,2706088,290,prior,28,6,10,7.0,196,16,1,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,45,Loyal Customer
94,1952286,331,prior,6,5,16,30.0,196,8,0,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,old,6,New Customer
95,3226575,360,prior,1,5,12,NaN,196,1,0,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,Most orders,new,1,New Customer
96,1469869,377,prior,3,5,17,3.0,196,9,0,...,7,9.0,both,High-range product,Regularly busy,Regularly busy,average orders,old,3,New Customer
97,1927023,387,prior,2,4,10,22.0,196,3,0,...,7,9.0,both,High-range product,Least busy,Slowest days,Most orders,old,2,New Customer
98,858092,420,prior,4,1,19,30.0,196,2,0,...,7,9.0,both,High-range product,Regularly busy,Busiest days,average orders,old,5,New Customer
99,119314,420,prior,5,3,19,16.0,196,2,1,...,7,9.0,both,High-range product,Regularly busy,Slowest days,average orders,old,5,New Customer

In [68]:
pd.options.display.max_rows = 60